In [2]:
import polars as pl
import numpy as np

# 2020

## Создаем список торгов

In [5]:
df = pl.read_excel(source='correct_data/correct_data_2020.xlsx')
df = df.select(['ИНН заказчика', 'Реестровый номер публикации'])
df = df.rename({'Реестровый номер публикации':'pub_num'})
df = df.unique().sort('pub_num')
df

shape: (63_634, 2)
┌───────────────┬─────────────────────┐
│ ИНН заказчика ┆ pub_num             │
│ ---           ┆ ---                 │
│ str           ┆ str                 │
╞═══════════════╪═════════════════════╡
│ 0276090428    ┆ 0101100001120000001 │
│ 2014030545    ┆ 0101100009420000001 │
│ 2014030545    ┆ 0101100009420000002 │
│ 0261014135    ┆ 0101200002320000001 │
│ 0261014135    ┆ 0101200002320000002 │
│ …             ┆ …                   │
│ 0276143694    ┆ 3961555             │
│ 0276143694    ┆ 3963183             │
│ 0276143694    ┆ 3963353             │
│ 0276143694    ┆ 3964329             │
│ 6315376946    ┆ 54383               │
└───────────────┴─────────────────────┘

In [9]:
df.write_excel()

## Проверяем сколько закупок по каждому фз

In [181]:
d = pl.read_excel('zakgov/data_for_parsing_2020.xlsx')
d

shape: (63_634, 2)
┌───────────────┬─────────────────────┐
│ ИНН заказчика ┆ pub_num             │
│ ---           ┆ ---                 │
│ str           ┆ str                 │
╞═══════════════╪═════════════════════╡
│ 0276090428    ┆ 0101100001120000001 │
│ 2014030545    ┆ 0101100009420000001 │
│ 2014030545    ┆ 0101100009420000002 │
│ 0261014135    ┆ 0101200002320000001 │
│ 0261014135    ┆ 0101200002320000002 │
│ …             ┆ …                   │
│ 0276143694    ┆ 3961555             │
│ 0276143694    ┆ 3963183             │
│ 0276143694    ┆ 3963353             │
│ 0276143694    ┆ 3964329             │
│ 6315376946    ┆ 54383               │
└───────────────┴─────────────────────┘

In [182]:
print(f"Закупки по 44/94 ФЗ: {d.filter(pl.col('pub_num').str.len_chars()==19).shape[0]}")
print(f"Закупки с других площадок: {d.filter(pl.col('pub_num').str.len_chars()==7).shape[0]}")
print(f"Закупки по 223 ФЗ: {d.filter(pl.col('pub_num').str.len_chars()==11).shape[0]}")

Закупки по 44/94 ФЗ: 12974
Закупки с других площадок: 1799
Закупки по 223 ФЗ: 48860

### Нашли тендеры с несколькими участниками

In [183]:
g = d.filter(pl.col('pub_num').str.len_chars()==19)
g = g.group_by(pl.col('pub_num')).agg(pl.col('ИНН заказчика').count().alias('n'))
dif_prices = g.filter(pl.col('n')>1)
dif_prices.filter(pl.col('pub_num')=='0131300045220000003')

shape: (1, 2)
┌─────────────────────┬─────┐
│ pub_num             ┆ n   │
│ ---                 ┆ --- │
│ str                 ┆ u32 │
╞═════════════════════╪═════╡
│ 0131300045220000003 ┆ 13  │
└─────────────────────┴─────┘

In [184]:
dif_prices.select(pl.col('n').sum())

shape: (1, 1)
┌─────┐
│ n   │
│ --- │
│ u32 │
╞═════╡
│ 350 │
└─────┘

## Парсинг 2020

In [168]:
import json

with open('zakgov/result_zakgov_2020.json', 'r') as f:
    data = json.load(f)


ozoik = pl.from_dicts(data)
ozoik

shape: (61_086, 5)
┌─────────────────────┬────────┬────────────────────────────────┬──────────────────┬─────────┐
│ pub_num             ┆ price  ┆ oz                             ┆ oik              ┆ no_info │
│ ---                 ┆ ---    ┆ ---                            ┆ ---              ┆ ---     │
│ str                 ┆ str    ┆ str                            ┆ str              ┆ i64     │
╞═════════════════════╪════════╪════════════════════════════════╪══════════════════╪═════════╡
│ 0101100001120000001 ┆        ┆                                ┆                  ┆ 0       │
│                     ┆ 2 000… ┆         20 000,00 РОССИЙСКИЙ … ┆                  ┆         │
│                     ┆        ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆             100… ┆         │
│ 0101200002320000001 ┆        ┆                                ┆                  ┆ 0       │
│                     ┆ 16 50… ┆         165 000,00 РОССИЙСКИЙ… ┆                  ┆         │
│                     ┆        ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆             825… ┆         │
│ 0101200002320000002 ┆        ┆                                ┆                  ┆ 0       │
│                     ┆ 4 000… ┆         40 000,00 РОССИЙСКИЙ … ┆                  ┆         │
│                     ┆        ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆       …          ┆         │
│ 0101200009320000001 ┆        ┆ null                           ┆                  ┆ 0       │
│                     ┆ 22 68… ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆             2 2… ┆         │
│ 0101100009420000002 ┆        ┆ null                           ┆                  ┆ 0       │
│                     ┆ 634 1… ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆                  ┆         │
│                     ┆        ┆                                ┆             31 … ┆         │
│ …                   ┆ …      ┆ …                              ┆ …                ┆ …       │
│ 32514569675         ┆        ┆ null                           ┆ null             ┆ 0       │
│                     ┆ …      ┆                                ┆                  ┆         │
│ 32514571035         ┆        ┆ null                           ┆ null             ┆ 0       │
│                     ┆ …      ┆                                ┆                  ┆         │
│ 32514570297         ┆        ┆ null                           ┆ null             ┆ 0       │
│                     ┆ …      ┆                                ┆                  ┆         │
│ 32514569911         ┆        ┆ null                           ┆ null             ┆ 0       │
│                     ┆ …      ┆                                ┆                  ┆         │
│ 32514570868         ┆        ┆ null                           ┆ null             ┆ 0       │
│                     ┆ …      ┆                                ┆                  ┆         │
└─────────────────────┴────────┴────────────────────────────────┴──────────────────┴─────────┘

In [169]:
ozoik = ozoik.drop('no_info')
ozoik = ozoik.select('pub_num', 'price')

In [132]:
ozoik.write_excel()

## Делаем нормальные значения цены

In [170]:
ozoik = ozoik.with_columns(
                            pl.col("price")
                            .str.replace_all(r"[^\d,]", "")  
                            .str.replace(",", ".")            
                            .cast(pl.Float64)                 
                            .alias("price_float")
                           )

In [171]:
ozoik = ozoik.select('pub_num', 'price_float')
ozoik = ozoik.rename({'pub_num': 'Реестровый номер публикации', 'price_float':'Стоимость(руб.) Заказчик'})

## Соединяем с основным датафреймом

In [225]:
data = pl.read_excel(source='correct_data/correct_data_2020.xlsx')
print(data.shape)
data.head(2)

(109900, 26)

shape: (2, 26)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечен ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ ие контра ┆ сейчас ┆ ---       │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта  ┆ кта, %    ┆ ---    ┆ i64       │
│         ┆            ┆ str        ┆ ---        ┆   ┆ (руб.)     ┆ ---       ┆ i64    ┆           │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆ f64       ┆        ┆           │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆           ┆        ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════╪═══════════╡
│ 2       ┆ ГБУЗ АО    ┆ 3018005693 ┆ 49120.0    ┆ … ┆ null       ┆ 0.05      ┆ 0      ┆ 0         │
│         ┆ "ГКБ №3"   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ ФГБУ       ┆ 7706433263 ┆ 420000.0   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "ВИМС"     ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴────────┴───────────┘

In [226]:
df_noprice = data.filter(pl.col('Стоимость(руб.) Заказчик').is_null())
df_noprice.shape

(36823, 26)

In [227]:
noprice_list = df_noprice.select(pl.col('Реестровый номер публикации').unique()).to_numpy().flatten()
diffprice_list = dif_prices.select(pl.col('pub_num').unique()).to_numpy().flatten()
print(noprice_list.shape, diffprice_list.shape)
print(np.sum(np.isin(noprice_list, diffprice_list)))

(11986,) (25,)
0

In [228]:
df_noprice = df_noprice.join(other=ozoik.unique(), on='Реестровый номер публикации', how='left')
print(df_noprice.shape)
df_noprice.head(2)

(36823, 27)

shape: (2, 27)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬───────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ РНП    ┆ РНП ранее ┆ Стоимость │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ сейчас ┆ ---       ┆ (руб.)    │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта, ┆ ---    ┆ i64       ┆ Заказчик_ │
│         ┆            ┆ str        ┆ ---        ┆   ┆ %          ┆ i64    ┆           ┆ right     │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆        ┆           ┆ ---       │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆        ┆           ┆ f64       │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪═══════════╪═══════════╡
│ 2       ┆ ООО "БСК"  ┆ 0273056757 ┆ null       ┆ … ┆ null       ┆ 0      ┆ 0         ┆ null      │
│ 2       ┆ ООО        ┆ 6319231042 ┆ null       ┆ … ┆ null       ┆ 0      ┆ 0         ┆ 330258.6  │
│         ┆ "САМЭСК"   ┆            ┆            ┆   ┆            ┆        ┆           ┆           │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴───────────┴───────────┘

In [229]:
names = df_noprice.columns
names =  names[:3]+names[26:27]+names[4:26]
df_noprice = df_noprice.select(names)
df_noprice = df_noprice.rename({'Стоимость(руб.) Заказчик_right':'Стоимость(руб.) Заказчик'})
print(df_noprice.shape)
df_noprice.head(2)

(36823, 26)

shape: (2, 26)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечен ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ ие контра ┆ сейчас ┆ ---       │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта  ┆ кта, %    ┆ ---    ┆ i64       │
│         ┆            ┆ str        ┆ ---        ┆   ┆ (руб.)     ┆ ---       ┆ i64    ┆           │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆ f64       ┆        ┆           │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆           ┆        ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════╪═══════════╡
│ 2       ┆ ООО "БСК"  ┆ 0273056757 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│ 2       ┆ ООО        ┆ 6319231042 ┆ 330258.6   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "САМЭСК"   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴────────┴───────────┘

In [230]:
newdf = pl.concat([data.filter(pl.col('Стоимость(руб.) Заказчик').is_not_null()), df_noprice])
newdf

shape: (109_900, 26)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечен ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ ие контра ┆ сейчас ┆ ---       │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта  ┆ кта, %    ┆ ---    ┆ i64       │
│         ┆            ┆ str        ┆ ---        ┆   ┆ (руб.)     ┆ ---       ┆ i64    ┆           │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆ f64       ┆        ┆           │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆           ┆        ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════╪═══════════╡
│ 2       ┆ ГБУЗ АО    ┆ 3018005693 ┆ 49120.0    ┆ … ┆ null       ┆ 0.05      ┆ 0      ┆ 0         │
│         ┆ "ГКБ №3"   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ ФГБУ       ┆ 7706433263 ┆ 420000.0   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "ВИМС"     ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ ИСПМ РАН   ┆ 7728021249 ┆ 366354.41  ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│ 1       ┆ ФГАОУ ДПО  ┆ 7718084063 ┆ 495702.0   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "АКАДЕМИЯ  ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ МИНПРОСВЕЩ ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ …          ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ ФКУ ИК-4   ┆ 1651020150 ┆ 215864.0   ┆ … ┆ 10793.2    ┆ 0.05      ┆ 0      ┆ 0         │
│         ┆ УФСИН      ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ РОССИИ ПО  ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ РЕСПУ…     ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ …       ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …      ┆ …         │
│ 2       ┆ АО "МОСВОД ┆ 7701984274 ┆ 4.8129e6   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ МАОУ СОШ № ┆ 3906045856 ┆ 768572.0   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ 38         ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ АО "ОЗК"   ┆ 7708632345 ┆ 7.30785e8  ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│ 2       ┆ МУП АГО    ┆ 3801006828 ┆ 9.015408e6 ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "АНГАРСКИЙ ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ ВОДОКАНАЛ" ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ ООО        ┆ 6319231042 ┆ 251039.28  ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "САМЭСК"   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴────────┴───────────┘

## Заполняем пропуски

In [234]:
new = newdf.with_columns(pl.when(pl.col('Стоимость(руб.) Заказчик').is_not_null() &
                                pl.col('Обеспечение заявки (руб.)').is_not_null() &
                                pl.col('Обеспечение заявки, %').is_null())
                            .then(pl.col('Обеспечение заявки (руб.)')/pl.col('Стоимость(руб.) Заказчик'))
                            .otherwise(pl.col('Обеспечение заявки, %'))
                            .alias('Обеспечение заявки, %'))
new = new.with_columns(pl.when(pl.col('Стоимость(руб.) Заказчик').is_not_null() &
                                pl.col('Обеспечение заявки (руб.)').is_null() &
                                pl.col('Обеспечение заявки, %').is_not_null())
                            .then(pl.col('Обеспечение заявки, %')*pl.col('Стоимость(руб.) Заказчик'))
                            .otherwise(pl.col('Обеспечение заявки (руб.)'))
                            .alias('Обеспечение заявки (руб.)'))

new = new.with_columns(pl.when(pl.col('Стоимость(руб.) Заказчик').is_not_null() &
                                pl.col('Обеспечение контракта (руб.)').is_not_null() &
                                pl.col('Обеспечение контракта, %').is_null())
                            .then(pl.col('Обеспечение контракта (руб.)')/pl.col('Стоимость(руб.) Заказчик'))
                            .otherwise(pl.col('Обеспечение контракта, %'))
                            .alias('Обеспечение контракта, %'))
new = new.with_columns(pl.when(pl.col('Стоимость(руб.) Заказчик').is_not_null() &
                                pl.col('Обеспечение контракта (руб.)').is_null() &
                                pl.col('Обеспечение контракта, %').is_not_null())
                            .then(pl.col('Обеспечение контракта, %')*pl.col('Стоимость(руб.) Заказчик'))
                            .otherwise(pl.col('Обеспечение контракта (руб.)'))
                            .alias('Обеспечение контракта (руб.)'))

In [236]:
new.shape

(109900, 26)

In [239]:
new.write_excel()

# 2015

## Создаем список торгов

In [7]:
df = pl.read_excel(source='correct_data/correct_data_2015.xlsx')
df = df.select(['ИНН заказчика', 'Реестровый номер публикации'])
df = df.rename({'Реестровый номер публикации':'pub_num'})
df = df.unique().sort('pub_num')
df

Could not determine dtype for column 5, falling back to string

shape: (161_243, 2)
┌───────────────┬──────────────┐
│ ИНН заказчика ┆ pub_num      │
│ ---           ┆ ---          │
│ str           ┆ str          │
╞═══════════════╪══════════════╡
│ 7451432207    ┆ 0321718002DP │
│ 7451432207    ┆ 0321718003DP │
│ 7710305634    ┆ 1000111      │
│ 7710305634    ┆ 1009211      │
│ 7710305634    ┆ 1030788      │
│ …             ┆ …            │
│ 7710305634    ┆ 966553       │
│ 7710305634    ┆ 970998       │
│ 7710305634    ┆ 973130       │
│ 7710305634    ┆ 974372       │
│ 7710305634    ┆ 997344       │
└───────────────┴──────────────┘

In [8]:
df = df.filter(pl.col('pub_num').str.len_chars()==11)
df

shape: (158_785, 2)
┌───────────────┬─────────────┐
│ ИНН заказчика ┆ pub_num     │
│ ---           ┆ ---         │
│ str           ┆ str         │
╞═══════════════╪═════════════╡
│ 6670480610    ┆ 31806697369 │
│ 5074070474    ┆ 31806713098 │
│ 5074070474    ┆ 31806713320 │
│ 5074070474    ┆ 31806713373 │
│ 5074070474    ┆ 31806722871 │
│ …             ┆ …           │
│ 5321062368    ┆ 32009107963 │
│ 5321062368    ┆ 32009108289 │
│ 5321062368    ┆ 32009108424 │
│ 7708131540    ┆ 32009155076 │
│ 7708131540    ┆ 32009199916 │
└───────────────┴─────────────┘

### Нашли тендеры с несколькими участниками

In [10]:
g = df.group_by(pl.col('pub_num')).agg(pl.col('ИНН заказчика').count().alias('n'))
dif_prices = g.filter(pl.col('n')>1)
dif_prices.shape

(121, 2)

In [17]:
dif_prices.head(3)

shape: (3, 2)
┌─────────────┬─────┐
│ pub_num     ┆ n   │
│ ---         ┆ --- │
│ str         ┆ u32 │
╞═════════════╪═════╡
│ 31806957852 ┆ 4   │
│ 31807154691 ┆ 2   │
│ 31807168641 ┆ 2   │
└─────────────┴─────┘

Убираем их

In [11]:
for_sure = g.filter(pl.col('n')==1)
for_sure.shape

(158244, 2)

In [15]:
forsure_df = df.join(for_sure, on='pub_num', how='left')
forsure_df = forsure_df.filter(pl.col('n').is_not_null()).drop('n')
forsure_df.head(2)

shape: (2, 2)
┌───────────────┬─────────────┐
│ ИНН заказчика ┆ pub_num     │
│ ---           ┆ ---         │
│ str           ┆ str         │
╞═══════════════╪═════════════╡
│ 6670480610    ┆ 31806697369 │
│ 5074070474    ┆ 31806713098 │
└───────────────┴─────────────┘

In [16]:
forsure_df.write_excel()

## Парсинг 2015

In [28]:
import json

with open('zakgov/result_zakgov_2015.json', 'r') as f:
    data = json.load(f)


ozoik = pl.from_dicts(data)
ozoik.shape

(147742, 5)

In [29]:
ozoik.null_count()

shape: (1, 5)
┌─────────┬───────┬────────┬────────┬─────────┐
│ pub_num ┆ price ┆ oz     ┆ oik    ┆ no_info │
│ ---     ┆ ---   ┆ ---    ┆ ---    ┆ ---     │
│ u32     ┆ u32   ┆ u32    ┆ u32    ┆ u32     │
╞═════════╪═══════╪════════╪════════╪═════════╡
│ 0       ┆ 0     ┆ 147742 ┆ 147742 ┆ 0       │
└─────────┴───────┴────────┴────────┴─────────┘

In [30]:
ozoik = ozoik.drop('no_info', 'oz', 'oik')
print(ozoik.shape)
ozoik.head(2)

(147742, 2)

shape: (2, 2)
┌─────────────┬────────────────────────────────┐
│ pub_num     ┆ price                          │
│ ---         ┆ ---                            │
│ str         ┆ str                            │
╞═════════════╪════════════════════════════════╡
│ 31806697369 ┆                                │
│             ┆                              … │
│ 31806713320 ┆                                │
│             ┆                              … │
└─────────────┴────────────────────────────────┘

## Делаем нормальные значения цены

In [31]:
ozoik = ozoik.with_columns(
                            pl.col("price")
                            .str.replace_all(r"[^\d,]", "")  
                            .str.replace(",", ".")            
                            .cast(pl.Float64)                 
                            .alias("price")
                           )
ozoik = ozoik.rename({'pub_num': 'Реестровый номер публикации', 'price':'Стоимость(руб.) Заказчик'})
ozoik.head(2)

shape: (2, 2)
┌─────────────────────────────┬──────────────────────────┐
│ Реестровый номер публикации ┆ Стоимость(руб.) Заказчик │
│ ---                         ┆ ---                      │
│ str                         ┆ f64                      │
╞═════════════════════════════╪══════════════════════════╡
│ 31806697369                 ┆ 1.1564e7                 │
│ 31806713320                 ┆ 964033.33                │
└─────────────────────────────┴──────────────────────────┘

## Соединяем с основным датафреймом

In [34]:
data = pl.read_excel(source='correct_data/correct_data_2015.xlsx')
print(data.shape)
data.head(2)

Could not determine dtype for column 5, falling back to string

(382178, 22)

shape: (2, 22)
┌─────────┬─────────────┬─────────────┬─────────────┬───┬────────────┬────────┬────────┬───────────┐
│ Уровень ┆ Заказчик    ┆ ИНН         ┆ Стоимость(р ┆ … ┆ Форма      ┆ Тип    ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---         ┆ заказчика   ┆ уб.)        ┆   ┆ публикации ┆ торгов ┆ сейчас ┆ ---       │
│ i64     ┆ str         ┆ ---         ┆ Заказчик    ┆   ┆ ---        ┆ ---    ┆ ---    ┆ i64       │
│         ┆             ┆ str         ┆ ---         ┆   ┆ str        ┆ str    ┆ i64    ┆           │
│         ┆             ┆             ┆ f64         ┆   ┆            ┆        ┆        ┆           │
╞═════════╪═════════════╪═════════════╪═════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ 1       ┆ АНО "ДФИКММ ┆ 7451432207  ┆ 1.4641e7    ┆ … ┆ Торговая   ┆ Иной   ┆ 0      ┆ 0         │
│         ┆ ЧО"         ┆             ┆             ┆   ┆ процедура  ┆ способ ┆        ┆           │
│ 2       ┆ АНО "ДФИКММ ┆ 7451432207  ┆ null        ┆ … ┆ Торговая   ┆ null   ┆ 0      ┆ 0         │
│         ┆ ЧО"         ┆             ┆             ┆   ┆ процедура  ┆        ┆        ┆           │
└─────────┴─────────────┴─────────────┴─────────────┴───┴────────────┴────────┴────────┴───────────┘

In [48]:
data.filter(pl.col('Стоимость(руб.) Заказчик').is_null()).shape

(319522, 22)

In [37]:
new = data.join(other=ozoik.unique(), on='Реестровый номер публикации', how='left')
print(new.shape)
new.head(2)

(382178, 23)

shape: (2, 23)
┌─────────┬─────────────┬─────────────┬─────────────┬───┬────────┬────────┬───────────┬────────────┐
│ Уровень ┆ Заказчик    ┆ ИНН         ┆ Стоимость(р ┆ … ┆ Тип    ┆ РНП    ┆ РНП ранее ┆ Стоимость( │
│ ---     ┆ ---         ┆ заказчика   ┆ уб.)        ┆   ┆ торгов ┆ сейчас ┆ ---       ┆ руб.) Зака │
│ i64     ┆ str         ┆ ---         ┆ Заказчик    ┆   ┆ ---    ┆ ---    ┆ i64       ┆ зчик_right │
│         ┆             ┆ str         ┆ ---         ┆   ┆ str    ┆ i64    ┆           ┆ ---        │
│         ┆             ┆             ┆ f64         ┆   ┆        ┆        ┆           ┆ f64        │
╞═════════╪═════════════╪═════════════╪═════════════╪═══╪════════╪════════╪═══════════╪════════════╡
│ 1       ┆ АНО "ДФИКММ ┆ 7451432207  ┆ 1.4641e7    ┆ … ┆ Иной   ┆ 0      ┆ 0         ┆ null       │
│         ┆ ЧО"         ┆             ┆             ┆   ┆ способ ┆        ┆           ┆            │
│ 2       ┆ АНО "ДФИКММ ┆ 7451432207  ┆ null        ┆ … ┆ null   ┆ 0      ┆ 0         ┆ null       │
│         ┆ ЧО"         ┆             ┆             ┆   ┆        ┆        ┆           ┆            │
└─────────┴─────────────┴─────────────┴─────────────┴───┴────────┴────────┴───────────┴────────────┘

In [42]:
new = new.with_columns(pl.when(pl.col('Стоимость(руб.) Заказчик').is_null() & pl.col('Стоимость(руб.) Заказчик_right').is_not_null())
                       .then(pl.col('Стоимость(руб.) Заказчик_right'))
                       .when(pl.col('Стоимость(руб.) Заказчик').is_not_null() & pl.col('Стоимость(руб.) Заказчик_right').is_null())
                       .then(pl.col('Стоимость(руб.) Заказчик'))
                       .when(pl.col('Стоимость(руб.) Заказчик').is_not_null() & pl.col('Стоимость(руб.) Заказчик_right').is_not_null())
                       .then(pl.col('Стоимость(руб.) Заказчик'))
                       .alias('price'))
print(new.shape)

(382178, 24)

In [49]:
new.columns

['Уровень',
 'Заказчик',
 'ИНН заказчика',
 'Стоимость(руб.) Заказчик',
 'Реестровый номер публикации',
 'Идентификационный код закупки',
 'Сфера деятельности',
 'Регион поставки',
 'Город поставки',
 'Дата публикации',
 'Дата окончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ',
 'Дата начала подачи заявок / Дата начала исполнения контракта / Дата публикации ППГ',
 'Дата окончания проведения торгов',
 'Поставщик',
 'ИНН поставщика',
 'Победитель',
 'Статус допуска',
 'Снижение на торгах,%',
 'Форма публикации',
 'Тип торгов',
 'РНП сейчас',
 'РНП ранее',
 'Стоимость(руб.) Заказчик_right',
 'price']

In [52]:
name = new.columns
name = name[0:3]+name[23:24]+name[4:22]
new = new.select(name)
print(new.shape)
new.head(2)

(382178, 22)

shape: (2, 22)
┌─────────┬─────────────┬────────────┬──────────┬───┬────────────┬────────┬────────────┬───────────┐
│ Уровень ┆ Заказчик    ┆ ИНН        ┆ price    ┆ … ┆ Форма      ┆ Тип    ┆ РНП сейчас ┆ РНП ранее │
│ ---     ┆ ---         ┆ заказчика  ┆ ---      ┆   ┆ публикации ┆ торгов ┆ ---        ┆ ---       │
│ i64     ┆ str         ┆ ---        ┆ f64      ┆   ┆ ---        ┆ ---    ┆ i64        ┆ i64       │
│         ┆             ┆ str        ┆          ┆   ┆ str        ┆ str    ┆            ┆           │
╞═════════╪═════════════╪════════════╪══════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 1       ┆ АНО "ДФИКММ ┆ 7451432207 ┆ 1.4641e7 ┆ … ┆ Торговая   ┆ Иной   ┆ 0          ┆ 0         │
│         ┆ ЧО"         ┆            ┆          ┆   ┆ процедура  ┆ способ ┆            ┆           │
│ 2       ┆ АНО "ДФИКММ ┆ 7451432207 ┆ null     ┆ … ┆ Торговая   ┆ null   ┆ 0          ┆ 0         │
│         ┆ ЧО"         ┆            ┆          ┆   ┆ процедура  ┆        ┆            ┆           │
└─────────┴─────────────┴────────────┴──────────┴───┴────────────┴────────┴────────────┴───────────┘

In [54]:
new = new.with_columns(pl.lit(None, dtype=pl.Float64).alias('Обеспечение заявки (руб.)'),
                      pl.lit(None, dtype=pl.Float64).alias('Обеспечение заявки, %'),
                      pl.lit(None, dtype=pl.Float64).alias('Обеспечение контракта (руб.)'),
                      pl.lit(None, dtype=pl.Float64).alias('Обеспечение контракта, %'))
new.head(1)

shape: (1, 26)
┌─────────┬────────────┬────────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ price    ┆ … ┆ Обеспечен ┆ Обеспечен ┆ Обеспечен ┆ Обеспечен │
│ ---     ┆ ---        ┆ заказчика  ┆ ---      ┆   ┆ ие заявки ┆ ие        ┆ ие        ┆ ие контра │
│ i64     ┆ str        ┆ ---        ┆ f64      ┆   ┆ (руб.)    ┆ заявки, % ┆ контракта ┆ кта, %    │
│         ┆            ┆ str        ┆          ┆   ┆ ---       ┆ ---       ┆ (руб.)    ┆ ---       │
│         ┆            ┆            ┆          ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│         ┆            ┆            ┆          ┆   ┆           ┆           ┆ f64       ┆           │
╞═════════╪════════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ АНО        ┆ 7451432207 ┆ 1.4641e7 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆ "ДФИКММ    ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
│         ┆ ЧО"        ┆            ┆          ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴────────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [55]:
new.columns

['Уровень',
 'Заказчик',
 'ИНН заказчика',
 'price',
 'Реестровый номер публикации',
 'Идентификационный код закупки',
 'Сфера деятельности',
 'Регион поставки',
 'Город поставки',
 'Дата публикации',
 'Дата окончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ',
 'Дата начала подачи заявок / Дата начала исполнения контракта / Дата публикации ППГ',
 'Дата окончания проведения торгов',
 'Поставщик',
 'ИНН поставщика',
 'Победитель',
 'Статус допуска',
 'Снижение на торгах,%',
 'Форма публикации',
 'Тип торгов',
 'РНП сейчас',
 'РНП ранее',
 'Обеспечение заявки (руб.)',
 'Обеспечение заявки, %',
 'Обеспечение контракта (руб.)',
 'Обеспечение контракта, %']

In [62]:
names = new.columns
names = names[:20] + names[22:] + names[20:22]
new = new.select(names)
print(new.shape)
new.head(2)

(382178, 26)

shape: (2, 26)
┌─────────┬─────────────┬────────────┬──────────┬───┬────────────┬────────────┬────────┬───────────┐
│ Уровень ┆ Заказчик    ┆ ИНН        ┆ price    ┆ … ┆ Обеспечени ┆ Обеспечени ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---         ┆ заказчика  ┆ ---      ┆   ┆ е          ┆ е          ┆ сейчас ┆ ---       │
│ i64     ┆ str         ┆ ---        ┆ f64      ┆   ┆ контракта  ┆ контракта, ┆ ---    ┆ i64       │
│         ┆             ┆ str        ┆          ┆   ┆ (руб.)     ┆ %          ┆ i64    ┆           │
│         ┆             ┆            ┆          ┆   ┆ ---        ┆ ---        ┆        ┆           │
│         ┆             ┆            ┆          ┆   ┆ f64        ┆ f64        ┆        ┆           │
╞═════════╪═════════════╪════════════╪══════════╪═══╪════════════╪════════════╪════════╪═══════════╡
│ 1       ┆ АНО "ДФИКММ ┆ 7451432207 ┆ 1.4641e7 ┆ … ┆ null       ┆ null       ┆ 0      ┆ 0         │
│         ┆ ЧО"         ┆            ┆          ┆   ┆            ┆            ┆        ┆           │
│ 2       ┆ АНО "ДФИКММ ┆ 7451432207 ┆ null     ┆ … ┆ null       ┆ null       ┆ 0      ┆ 0         │
│         ┆ ЧО"         ┆            ┆          ┆   ┆            ┆            ┆        ┆           │
└─────────┴─────────────┴────────────┴──────────┴───┴────────────┴────────────┴────────┴───────────┘

In [ ]:
new = new.rename({'price':'Стоимость(руб.) Заказчик'})

In [71]:
new.write_excel()

In [73]:
new.null_count()

shape: (1, 26)
┌─────────┬──────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────┬───────────┐
│ Уровень ┆ Заказчик ┆ ИНН         ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечени ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---      ┆ заказчика   ┆ руб.)      ┆   ┆ е          ┆ е          ┆ сейчас ┆ ---       │
│ u32     ┆ u32      ┆ ---         ┆ Заказчик   ┆   ┆ контракта  ┆ контракта, ┆ ---    ┆ u32       │
│         ┆          ┆ u32         ┆ ---        ┆   ┆ (руб.)     ┆ %          ┆ u32    ┆           │
│         ┆          ┆             ┆ u32        ┆   ┆ ---        ┆ ---        ┆        ┆           │
│         ┆          ┆             ┆            ┆   ┆ u32        ┆ u32        ┆        ┆           │
╞═════════╪══════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════╪═══════════╡
│ 0       ┆ 0        ┆ 0           ┆ 39818      ┆ … ┆ 382178     ┆ 382178     ┆ 0      ┆ 0         │
└─────────┴──────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────┴───────────┘

In [72]:
print(new.shape, data.shape)

(382178, 26) (382178, 22)

In [74]:
data.null_count()

shape: (1, 22)
┌─────────┬──────────┬─────────────┬────────────┬───┬────────────┬────────┬────────────┬───────────┐
│ Уровень ┆ Заказчик ┆ ИНН         ┆ Стоимость( ┆ … ┆ Форма      ┆ Тип    ┆ РНП сейчас ┆ РНП ранее │
│ ---     ┆ ---      ┆ заказчика   ┆ руб.)      ┆   ┆ публикации ┆ торгов ┆ ---        ┆ ---       │
│ u32     ┆ u32      ┆ ---         ┆ Заказчик   ┆   ┆ ---        ┆ ---    ┆ u32        ┆ u32       │
│         ┆          ┆ u32         ┆ ---        ┆   ┆ u32        ┆ u32    ┆            ┆           │
│         ┆          ┆             ┆ u32        ┆   ┆            ┆        ┆            ┆           │
╞═════════╪══════════╪═════════════╪════════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ 0       ┆ 0        ┆ 0           ┆ 319522     ┆ … ┆ 0          ┆ 321261 ┆ 0          ┆ 0         │
└─────────┴──────────┴─────────────┴────────────┴───┴────────────┴────────┴────────────┴───────────┘

In [76]:
data.shape[0]-39818

342360

нашли много данных по ценам)

## Делаем нормальные значения oz и oik

In [61]:
ozoik = ozoik.rename({'oz':'обеспечение заявки', 
                      'oik':'обеспечение исполнения контракта',  
                      'pub_num':'Реестровый номер публикации'})

In [62]:
# исправляем oz
ozoik = ozoik.with_columns(pl.col("обеспечение заявки")
                                   .str.extract(r"([\d\xa0,]+)")
                                   .str.replace_all("\xa0", "")
                                   .str.replace(",", ".")
                                   .cast(pl.Float64)
                                   .alias("обеспечение заявки"))

In [63]:
# сиправляем oik
ozoik = ozoik.with_columns(
                    pl.col("обеспечение исполнения контракта")
                    .str.extract(r'([\d\xa0,]+)\s*₽')
                    .str.replace_all(r'[\xa0,]', '')
                    .cast(pl.Float64)
                    .alias("numeric_value"),
                
                    pl.col("обеспечение исполнения контракта")
                    .str.extract(r'\(?(\d+,\d+|\d+)\s*%\)?')
                    .str.replace(',', '.')
                    .cast(pl.Float64)
                    .alias("percentage_value"))

#ozoik = ozoik.with_columns(pl.when((pl.col('numeric_value').is_not_null()) & (pl.col('percentage_value').is_not_null())).then(pl.lit(None)).otherwise(pl.col('numeric_value')).alias('numeric_value'))

ozoik = ozoik.rename({'numeric_value':'обеспечение исполнения контракта, руб', 'percentage_value': 'обеспечение исполнения контракта, %'})
ozoik = ozoik.with_columns(pl.col('обеспечение исполнения контракта, %')/100)
ozoik

shape: (12_974, 6)
┌───────────────────────┬─────────────┬─────────────┬─────────┬─────────────┬──────────────────────┐
│ Реестровый номер      ┆ обеспечение ┆ обеспечение ┆ no_info ┆ обеспечение ┆ обеспечение          │
│ публикации            ┆ заявки      ┆ исполнения  ┆ ---     ┆ исполнения  ┆ исполнения контрак…  │
│ ---                   ┆ ---         ┆ контрак…    ┆ i64     ┆ контрак…    ┆ ---                  │
│ str                   ┆ f64         ┆ ---         ┆         ┆ ---         ┆ f64                  │
│                       ┆             ┆ str         ┆         ┆ f64         ┆                      │
╞═══════════════════════╪═════════════╪═════════════╪═════════╪═════════════╪══════════════════════╡
│ 0101100001120000001   ┆ 20000.0     ┆             ┆ 0       ┆ 1e7         ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆ 100…        ┆         ┆             ┆                      │
│ 0101100009420000002   ┆ null        ┆             ┆ 0       ┆ 3.170953e6  ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆ 31 …        ┆         ┆             ┆                      │
│ 0101200002320000002   ┆ 40000.0     ┆             ┆ 0       ┆ null        ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆       …     ┆         ┆             ┆                      │
│ 0101100009420000001   ┆ null        ┆             ┆ 0       ┆ 4.952138e6  ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆ 49 …        ┆         ┆             ┆                      │
│ 0101200008020000001   ┆ null        ┆             ┆ 0       ┆ null        ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆       …     ┆         ┆             ┆                      │
│ …                     ┆ …           ┆ …           ┆ …       ┆ …           ┆ …                    │
│ 2071500000120000002   ┆ null        ┆             ┆ 0       ┆ 2.802586e6  ┆ null                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆ 28 …        ┆         ┆             ┆                      │
│ 2074700000120000001   ┆ 14400.0     ┆             ┆ 0       ┆ null        ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆       …     ┆         ┆             ┆                      │
│ 2084700000120000001   ┆ null        ┆             ┆ 0       ┆ null        ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆       …     ┆         ┆             ┆                      │
│ 2078500000120000003   ┆ 24094.26    ┆             ┆ 0       ┆ 1.204713e7  ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆ 120…        ┆         ┆             ┆                      │
│ 2084700000120000002   ┆ null        ┆             ┆ 0       ┆ null        ┆ 0.05                 │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆             ┆         ┆             ┆                      │
│                       ┆             ┆       …     ┆         ┆             ┆                      │
└───────────────────────┴─────────────┴─────────────┴─────────┴─────────────┴──────────────────────┘

In [64]:
ozoik = ozoik.drop('no_info')

## Соединяем с основным датафреймом

In [65]:
data = pl.read_excel(source='correct_data/correct_data_2020.xlsx')
data.shape

(109900, 26)

In [66]:
data = data.join(other=ozoik.unique('Реестровый номер публикации'), how='left', on=['Реестровый номер публикации'])
data

shape: (109_900, 30)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН       ┆ Стоимость ┆ … ┆ обеспечен ┆ обеспечен ┆ обеспечен ┆ обеспечен │
│ ---     ┆ ---        ┆ заказчика ┆ (руб.)    ┆   ┆ ие заявки ┆ ие исполн ┆ ие исполн ┆ ие исполн │
│ i64     ┆ str        ┆ ---       ┆ Заказчик  ┆   ┆ ---       ┆ ения      ┆ ения      ┆ ения      │
│         ┆            ┆ str       ┆ ---       ┆   ┆ f64       ┆ контрак…  ┆ контрак…  ┆ контрак…  │
│         ┆            ┆           ┆ f64       ┆   ┆           ┆ ---       ┆ ---       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆ str       ┆ f64       ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2       ┆ ГБУЗ АО    ┆ 301800569 ┆ 49120.0   ┆ … ┆ null      ┆           ┆ null      ┆ 0.05      │
│         ┆ "ГКБ №3"   ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆       …   ┆           ┆           │
│ 1       ┆ ФГБУ       ┆ 770643326 ┆ 420000.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆ "ВИМС"     ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2       ┆ ООО "БСК"  ┆ 027305675 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆            ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1       ┆ ИСПМ РАН   ┆ 772802124 ┆ 366354.41 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆            ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1       ┆ ФГАОУ ДПО  ┆ 771808406 ┆ 495702.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆ "АКАДЕМИЯ  ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ МИНПРОСВЕЩ ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ …          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2       ┆ ГКБСМП     ┆ 390604084 ┆ 96283.83  ┆ … ┆ null      ┆           ┆ null      ┆ 0.05      │
│         ┆            ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆       …   ┆           ┆           │
│ 1       ┆ КГКУ       ┆ 271301220 ┆ 519830.0  ┆ … ┆ null      ┆           ┆ 2.59915e6 ┆ 0.05      │
│         ┆ ХОРСКИЙ    ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ СРЦ        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆ 25 …      ┆           ┆           │
│ 2       ┆ КОМИТЕТ    ┆ 290201200 ┆ 5.922485e ┆ … ┆ 59224.85  ┆           ┆ null      ┆ 0.15      │
│         ┆ ЖКХ, ТИС   ┆ 8         ┆ 6         ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆       …   ┆           ┆           │
│ 2       ┆ ГКУ КК ЦЗН ┆ 233002793 ┆ 91333.32  ┆ … ┆ 913.33    ┆           ┆ null      ┆ 0.05      │
│         ┆ ДИНСКОГО   ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆ РАЙОНА     ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆       …   ┆           ┆           │
│ 2       ┆ ООО        ┆ 631923104 ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│         ┆ "САМЭСК"   ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [89]:
check_oik = data.with_columns(pl.when(pl.col('Обеспечение контракта (руб.)').is_not_null()).then(1).otherwise(0).alias('oldr'))
check_oik = check_oik.with_columns(pl.when(pl.col('Обеспечение контракта, %').is_not_null()).then(1).otherwise(0).alias('oldpr'))
check_oik = check_oik.with_columns((pl.col('oldr')+pl.col('oldpr')).alias('old'))
check_oik = check_oik.with_columns(pl.when(pl.col('old')>0).then(1).otherwise(0).alias('old'))

check_oik = check_oik.with_columns(pl.when(pl.col('обеспечение исполнения контракта, руб').is_not_null()).then(1).otherwise(0).alias('newr'))
check_oik = check_oik.with_columns(pl.when(pl.col('обеспечение исполнения контракта, %').is_not_null()).then(1).otherwise(0).alias('newpr'))
check_oik = check_oik.with_columns((pl.col('newr')+pl.col('newpr')).alias('new'))
check_oik = check_oik.with_columns(pl.when(pl.col('new')>0).then(1).otherwise(0).alias('new'))
check_oik = check_oik.drop(['oldr','oldpr', 'newr', 'newpr'])
check_oik.filter(pl.col('old')!=pl.col('new'))

shape: (0, 32)
┌─────────┬──────────┬───────────┬────────────────┬───┬────────────────┬───────────────┬─────┬─────┐
│ Уровень ┆ Заказчик ┆ ИНН       ┆ Стоимость(руб. ┆ … ┆ обеспечение    ┆ обеспечение   ┆ old ┆ new │
│ ---     ┆ ---      ┆ заказчика ┆ ) Заказчик     ┆   ┆ исполнения     ┆ исполнения    ┆ --- ┆ --- │
│ i64     ┆ str      ┆ ---       ┆ ---            ┆   ┆ контрак…       ┆ контрак…      ┆ i32 ┆ i32 │
│         ┆          ┆ str       ┆ f64            ┆   ┆ ---            ┆ ---           ┆     ┆     │
│         ┆          ┆           ┆                ┆   ┆ f64            ┆ f64           ┆     ┆     │
╞═════════╪══════════╪═══════════╪════════════════╪═══╪════════════════╪═══════════════╪═════╪═════╡
└─────────┴──────────┴───────────┴────────────────┴───┴────────────────┴───────────────┴─────┴─────┘

короче, ничего нового не нашли(

In [91]:
check_oz = data.with_columns(pl.when(pl.col('Обеспечение заявки (руб.)').is_not_null()).then(1).otherwise(0).alias('oldr'))
check_oz = check_oz.with_columns(pl.when(pl.col('Обеспечение заявки, %').is_not_null()).then(1).otherwise(0).alias('oldpr'))
check_oz = check_oz.with_columns((pl.col('oldr')+pl.col('oldpr')).alias('old'))
check_oz = check_oz.with_columns(pl.when(pl.col('old')>0).then(1).otherwise(0).alias('old'))

check_oz = check_oz.with_columns(pl.when(pl.col('обеспечение заявки').is_not_null()).then(1).otherwise(0).alias('new'))
check_oz = check_oz.drop(['oldr','oldpr'])
check_oz.filter(pl.col('old')!=pl.col('new'))

shape: (4_353, 32)
┌─────────┬──────────────┬──────────────┬──────────────┬───┬─────────────┬─────────────┬─────┬─────┐
│ Уровень ┆ Заказчик     ┆ ИНН          ┆ Стоимость(ру ┆ … ┆ обеспечение ┆ обеспечение ┆ old ┆ new │
│ ---     ┆ ---          ┆ заказчика    ┆ б.) Заказчик ┆   ┆ исполнения  ┆ исполнения  ┆ --- ┆ --- │
│ i64     ┆ str          ┆ ---          ┆ ---          ┆   ┆ контрак…    ┆ контрак…    ┆ i32 ┆ i32 │
│         ┆              ┆ str          ┆ f64          ┆   ┆ ---         ┆ ---         ┆     ┆     │
│         ┆              ┆              ┆              ┆   ┆ f64         ┆ f64         ┆     ┆     │
╞═════════╪══════════════╪══════════════╪══════════════╪═══╪═════════════╪═════════════╪═════╪═════╡
│ 2       ┆ АО "ИЭМЗ     ┆ 1831083343   ┆ null         ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│         ┆ "КУПОЛ"      ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│ 1       ┆ АО "МОСВОДОК ┆ 7701984274   ┆ 3.8429e7     ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│         ┆ АНАЛ"        ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│ 2       ┆ АО "МОСВОДОК ┆ 7701984274   ┆ null         ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│         ┆ АНАЛ"        ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│ 2       ┆ АО "МОСВОДОК ┆ 7701984274   ┆ null         ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│         ┆ АНАЛ"        ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│ 1       ┆ МУП АГО      ┆ 3801006828   ┆ 659411.44    ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│         ┆ "АНГАРСКИЙ   ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│         ┆ ВОДОКАНАЛ"   ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│ …       ┆ …            ┆ …            ┆ …            ┆ … ┆ …           ┆ …           ┆ …   ┆ …   │
│ 1       ┆ АО "ВОЭ"     ┆ 3443029580   ┆ 1.2291e7     ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│ 1       ┆ АО "ОЗК"     ┆ 7708632345   ┆ 1.4832e8     ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│ 2       ┆ БАНК ВТБ     ┆ 7702070139   ┆ null         ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│         ┆ (ПАО)        ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│ 2       ┆ АО "ОЗК"     ┆ 7708632345   ┆ null         ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│ 2       ┆ МУП АГО      ┆ 3801006828   ┆ null         ┆ … ┆ null        ┆ null        ┆ 1   ┆ 0   │
│         ┆ "АНГАРСКИЙ   ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
│         ┆ ВОДОКАНАЛ"   ┆              ┆              ┆   ┆             ┆             ┆     ┆     │
└─────────┴──────────────┴──────────────┴──────────────┴───┴─────────────┴─────────────┴─────┴─────┘

все максимально печально

In [103]:
check_oz.filter(pl.col('Реестровый номер публикации')=='32110158113')

shape: (7, 32)
┌─────────┬──────────┬───────────────┬───────────────┬───┬──────────────┬──────────────┬─────┬─────┐
│ Уровень ┆ Заказчик ┆ ИНН заказчика ┆ Стоимость(руб ┆ … ┆ обеспечение  ┆ обеспечение  ┆ old ┆ new │
│ ---     ┆ ---      ┆ ---           ┆ .) Заказчик   ┆   ┆ исполнения   ┆ исполнения   ┆ --- ┆ --- │
│ i64     ┆ str      ┆ str           ┆ ---           ┆   ┆ контрак…     ┆ контрак…     ┆ i32 ┆ i32 │
│         ┆          ┆               ┆ f64           ┆   ┆ ---          ┆ ---          ┆     ┆     │
│         ┆          ┆               ┆               ┆   ┆ f64          ┆ f64          ┆     ┆     │
╞═════════╪══════════╪═══════════════╪═══════════════╪═══╪══════════════╪══════════════╪═════╪═════╡
│ 2       ┆ БАНК ВТБ ┆ 7702070139    ┆ null          ┆ … ┆ null         ┆ null         ┆ 1   ┆ 0   │
│         ┆ (ПАО)    ┆               ┆               ┆   ┆              ┆              ┆     ┆     │
│ 2       ┆ БАНК ВТБ ┆ 7702070139    ┆ null          ┆ … ┆ null         ┆ null         ┆ 1   ┆ 0   │
│         ┆ (ПАО)    ┆               ┆               ┆   ┆              ┆              ┆     ┆     │
│ 2       ┆ БАНК ВТБ ┆ 7702070139    ┆ null          ┆ … ┆ null         ┆ null         ┆ 1   ┆ 0   │
│         ┆ (ПАО)    ┆               ┆               ┆   ┆              ┆              ┆     ┆     │
│ 2       ┆ БАНК ВТБ ┆ 7702070139    ┆ null          ┆ … ┆ null         ┆ null         ┆ 1   ┆ 0   │
│         ┆ (ПАО)    ┆               ┆               ┆   ┆              ┆              ┆     ┆     │
│ 2       ┆ БАНК ВТБ ┆ 7702070139    ┆ null          ┆ … ┆ null         ┆ null         ┆ 1   ┆ 0   │
│         ┆ (ПАО)    ┆               ┆               ┆   ┆              ┆              ┆     ┆     │
│ 2       ┆ БАНК ВТБ ┆ 7702070139    ┆ null          ┆ … ┆ null         ┆ null         ┆ 1   ┆ 0   │
│         ┆ (ПАО)    ┆               ┆               ┆   ┆              ┆              ┆     ┆     │
│ 2       ┆ БАНК ВТБ ┆ 7702070139    ┆ null          ┆ … ┆ null         ┆ null         ┆ 1   ┆ 0   │
│         ┆ (ПАО)    ┆               ┆               ┆   ┆              ┆              ┆     ┆     │
└─────────┴──────────┴───────────────┴───────────────┴───┴──────────────┴──────────────┴─────┴─────┘

## Заполним пропуски

In [92]:
data = pl.read_excel(source='correct_data/correct_data_2020.xlsx')

In [93]:
data.columns

['Уровень',
 'Заказчик',
 'ИНН заказчика',
 'Стоимость(руб.) Заказчик',
 'Реестровый номер публикации',
 'Идентификационный код закупки',
 'Сфера деятельности',
 'Регион поставки',
 'Город поставки',
 'Дата публикации',
 'Дата окончания приема заявок / Дата планового окончания исполнения контракта / Плановая дата публикации лота по ППГ',
 'Дата начала подачи заявок / Дата начала исполнения контракта / Дата публикации ППГ',
 'Дата окончания проведения торгов',
 'Поставщик',
 'ИНН поставщика',
 'Победитель',
 'Статус допуска',
 'Снижение на торгах,%',
 'Форма публикации',
 'Тип торгов',
 'Обеспечение заявки (руб.)',
 'Обеспечение заявки, %',
 'Обеспечение контракта (руб.)',
 'Обеспечение контракта, %',
 'РНП сейчас',
 'РНП ранее']

In [94]:
data.filter(pl.col('Стоимость(руб.) Заказчик').is_not_null() & 
            pl.col('Обеспечение заявки (руб.)').is_not_null() &
            pl.col('Обеспечение заявки, %').is_null())

shape: (2_340, 26)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечен ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ ие контра ┆ сейчас ┆ ---       │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта  ┆ кта, %    ┆ ---    ┆ i64       │
│         ┆            ┆ str        ┆ ---        ┆   ┆ (руб.)     ┆ ---       ┆ i64    ┆           │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆ f64       ┆        ┆           │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆           ┆        ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════╪═══════════╡
│ 1       ┆ ОГКУ       ┆ 3906147174 ┆ 3.0000e6   ┆ … ┆ 149999.93  ┆ null      ┆ 0      ┆ 0         │
│         ┆ "ЦЕНТР     ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ СОЦИАЛЬНОЙ ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ ПОДДЕРЖ…   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ АО "МОСВОД ┆ 7701984274 ┆ 3.8429e7   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ АДМИНИСТРА ┆ 5513001802 ┆ 1.541188e6 ┆ … ┆ 77059.4    ┆ null      ┆ 0      ┆ 0         │
│         ┆ ЦИЯ ЗНАМЕН ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ СКОГО      ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ МУНИ…      ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ МУП АГО    ┆ 3801006828 ┆ 659411.44  ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "АНГАРСКИЙ ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ ВОДОКАНАЛ" ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ АО "МОСВОД ┆ 7701984274 ┆ 1.7820e7   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ …       ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …      ┆ …         │
│ 1       ┆ ГУ-ТОМСКОЕ ┆ 7018003855 ┆ 259529.78  ┆ … ┆ 12976.49   ┆ null      ┆ 0      ┆ 0         │
│         ┆ РО ФОНДА   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ СОЦИАЛЬНОГ ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ …          ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ АДМИНИСТРА ┆ 1433017567 ┆ 3.9083e6   ┆ … ┆ 195415.71  ┆ null      ┆ 0      ┆ 0         │
│         ┆ ЦИЯ МР "МИ ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ РНИНСКИЙ   ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ Р…         ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ АО "МОСВОД ┆ 7701984274 ┆ 2.0783e7   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 1       ┆ АО "ВОЭ"   ┆ 3443029580 ┆ 1.2291e7   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│ 1       ┆ АО "ОЗК"   ┆ 7708632345 ┆ 1.4832e8   ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴────────┴───────────┘

In [101]:
data.filter(pl.col('Стоимость(руб.) Заказчик').is_null() & 
            pl.col('Обеспечение заявки (руб.)').is_not_null())

shape: (3_252, 26)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬────────┬───────────┐
│ Уровень ┆ Заказчик   ┆ ИНН        ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечен ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---        ┆ заказчика  ┆ руб.)      ┆   ┆ е          ┆ ие контра ┆ сейчас ┆ ---       │
│ i64     ┆ str        ┆ ---        ┆ Заказчик   ┆   ┆ контракта  ┆ кта, %    ┆ ---    ┆ i64       │
│         ┆            ┆ str        ┆ ---        ┆   ┆ (руб.)     ┆ ---       ┆ i64    ┆           │
│         ┆            ┆            ┆ f64        ┆   ┆ ---        ┆ f64       ┆        ┆           │
│         ┆            ┆            ┆            ┆   ┆ f64        ┆           ┆        ┆           │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════╪═══════════╡
│ 2       ┆ АО "ИЭМЗ   ┆ 1831083343 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "КУПОЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ АО "МОСВОД ┆ 7701984274 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ АО "МОСВОД ┆ 7701984274 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ АО "МОСВОД ┆ 7701984274 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ АО "МОСВОД ┆ 7701984274 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ …       ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …      ┆ …         │
│ 2       ┆ МУП "ВОДОК ┆ 6608001915 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ АНАЛ"      ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ АО "МОСВОД ┆ 7701984274 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ ОКАНАЛ"    ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ БАНК ВТБ   ┆ 7702070139 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ (ПАО)      ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│ 2       ┆ АО "ОЗК"   ┆ 7708632345 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│ 2       ┆ МУП АГО    ┆ 3801006828 ┆ null       ┆ … ┆ null       ┆ null      ┆ 0      ┆ 0         │
│         ┆ "АНГАРСКИЙ ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
│         ┆ ВОДОКАНАЛ" ┆            ┆            ┆   ┆            ┆           ┆        ┆           │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴────────┴───────────┘

In [104]:
data.null_count()

shape: (1, 26)
┌─────────┬──────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────┬───────────┐
│ Уровень ┆ Заказчик ┆ ИНН         ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечени ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---      ┆ заказчика   ┆ руб.)      ┆   ┆ е          ┆ е          ┆ сейчас ┆ ---       │
│ u32     ┆ u32      ┆ ---         ┆ Заказчик   ┆   ┆ контракта  ┆ контракта, ┆ ---    ┆ u32       │
│         ┆          ┆ u32         ┆ ---        ┆   ┆ (руб.)     ┆ %          ┆ u32    ┆           │
│         ┆          ┆             ┆ u32        ┆   ┆ ---        ┆ ---        ┆        ┆           │
│         ┆          ┆             ┆            ┆   ┆ u32        ┆ u32        ┆        ┆           │
╞═════════╪══════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════╪═══════════╡
│ 0       ┆ 0        ┆ 0           ┆ 36823      ┆ … ┆ 95890      ┆ 79832      ┆ 0      ┆ 0         │
└─────────┴──────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────┴───────────┘

In [95]:
new = data.with_columns(pl.when(pl.col('Стоимость(руб.) Заказчик').is_not_null() &
                                pl.col('Обеспечение заявки (руб.)').is_not_null() &
                                pl.col('Обеспечение заявки, %').is_null())
                            .then(pl.col('Обеспечение заявки (руб.)')/pl.col('Стоимость(руб.) Заказчик'))
                            .otherwise(pl.col('Обеспечение заявки, %'))
                            .alias('Обеспечение заявки, %'))
new = new.with_columns(pl.when(pl.col('Стоимость(руб.) Заказчик').is_not_null() &
                                pl.col('Обеспечение заявки (руб.)').is_null() &
                                pl.col('Обеспечение заявки, %').is_not_null())
                            .then(pl.col('Обеспечение заявки, %')*pl.col('Стоимость(руб.) Заказчик'))
                            .otherwise(pl.col('Обеспечение заявки (руб.)'))
                            .alias('Обеспечение заявки (руб.)'))

In [97]:
new.filter(pl.col('Реестровый номер публикации')=='32009394462')

shape: (1, 26)
┌─────────┬──────────┬─────────────┬────────────┬───┬────────────┬────────────┬────────┬───────────┐
│ Уровень ┆ Заказчик ┆ ИНН         ┆ Стоимость( ┆ … ┆ Обеспечени ┆ Обеспечени ┆ РНП    ┆ РНП ранее │
│ ---     ┆ ---      ┆ заказчика   ┆ руб.)      ┆   ┆ е          ┆ е          ┆ сейчас ┆ ---       │
│ i64     ┆ str      ┆ ---         ┆ Заказчик   ┆   ┆ контракта  ┆ контракта, ┆ ---    ┆ i64       │
│         ┆          ┆ str         ┆ ---        ┆   ┆ (руб.)     ┆ %          ┆ i64    ┆           │
│         ┆          ┆             ┆ f64        ┆   ┆ ---        ┆ ---        ┆        ┆           │
│         ┆          ┆             ┆            ┆   ┆ f64        ┆ f64        ┆        ┆           │
╞═════════╪══════════╪═════════════╪════════════╪═══╪════════════╪════════════╪════════╪═══════════╡
│ 1       ┆ АО "ВОЭ" ┆ 3443029580  ┆ 1.2291e7   ┆ … ┆ null       ┆ null       ┆ 0      ┆ 0         │
└─────────┴──────────┴─────────────┴────────────┴───┴────────────┴────────────┴────────┴───────────┘

In [170]:
df.loc[291:294]

           inn      price                 num
291  223003534  124010.00  301300403220000000
292  224003713  491872.08  301300001120000000
293  224003713  665000.00  301300001120000000
294  224003713  850000.00  301300001120000000